name: linter

on: push

steps:
  - uses: actions/checkout@v2
  - name: Use Node.js
    uses: actions/setup-node@v1
    with:
      node-version: '14.x'
  - run: npm install --only=dev
  - run: make lint
